<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22472" started-at="2017-09-15T08:59:14Z" finished-at="2017-09-15T08:59:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22472" started-at="2017-09-15T08:59:14Z" finished-at="2017-09-15T08:59:37Z">
      <class name="testcase.BaseData.salesAreaManage">
        <test-method status="PASS" signature="openFireFox()[pri:0, instance:testcase.BaseData.salesAreaManage@8bd1b6a]" name="openFireFox" is-config="true" duration-ms="6722" started-at="2017-09-15T16:59:14Z" finished-at="2017-09-15T16:59:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openFireFox -->
        <test-method status="PASS" signature="logIn()[pri:1, instance:testcase.BaseData.salesAreaManage@8bd1b6a]" name="logIn" duration-ms="3537" started-at="2017-09-15T16:59:21Z" finished-at="2017-09-15T16:59:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logIn -->
        <test-method status="FAIL" signature="leadinSalesarea()[pri:2, instance:testcase.BaseData.salesAreaManage@8bd1b6a]" name="leadinSalesarea" duration-ms="12198" started-at="2017-09-15T16:59:24Z" finished-at="2017-09-15T16:59:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testcase.BaseData.salesAreaManage.leadinSalesarea(salesAreaManage.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- leadinSalesarea -->
      </class> <!-- testcase.BaseData.salesAreaManage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
